# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hates_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
