# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180626_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-publication_date',)},
        ),
    ]
