# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180627_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
